services:
  backend:
    container_name: backend-container
    restart: always
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
      
  frontend:
    container_name: frontend-container
    restart: always
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    command: ["serve", "-s", "/app", "-l", "3000"]

  db:
    image: postgres:15-alpine
    container_name: db-container
    restart: always
    environment:
      POSTGRES_DB: nba_notifier
      POSTGRES_USER: top_user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U top_user -d nba_notifier"]
      interval: 10s
      retries: 5

    ports:
      - "5432:5432"
      

volumes:
    db_data:
        
